import { promises as fs } from "node:fs";
import * as path from "node:path";
import { detectConfigs, kindLabel } from "./detect.ts";
import type { AgentConfigKind } from "./detect.ts";
import { readVersion } from "./version.ts";
import type { VersionInfo } from "./version.ts";

export interface DoctorCheck {
  name: string;
  ok: boolean;
  detail: string;
}

export interface DoctorReport {
  target: string;
  node: { version: string; ok: boolean; required: string };
  agentsmd: VersionInfo;
  configs: { kind: AgentConfigKind; label: string; path: string; bytes: number }[];
  agentsMd: {
    present: boolean;
    bytes: number;
    hasBanner: boolean;
    lastModifiedDaysAgo: number | null;
  };
  checks: DoctorCheck[];
  ok: boolean;
}

const REQUIRED_NODE_MAJOR = 22;
const BANNER_PATTERN = /generated by agentsmd|<!--\s*agentsmd/i;

function parseNodeMajor(v: string): number {
  const m = v.replace(/^v/, "").split(".")[0];
  return Number.parseInt(m, 10) || 0;
}

export async function runDoctor(root: string, nodeVersion: string = process.version): Promise<DoctorReport> {
  const nodeMajor = parseNodeMajor(nodeVersion);
  const nodeOk = nodeMajor >= REQUIRED_NODE_MAJOR;

  let agentsmd: VersionInfo;
  try {
    agentsmd = await readVersion();
  } catch {
    agentsmd = { name: "agentsmd", version: "unknown", source: "" };
  }
  const files = await detectConfigs(root);
  const configs: DoctorReport["configs"] = [];
  for (const f of files) {
    const st = await fs.stat(f.path);
    configs.push({ kind: f.kind, label: kindLabel(f.kind), path: f.path, bytes: st.size });
  }

  const agentsMdPath = path.join(root, "AGENTS.md");
  let present = false;
  let bytes = 0;
  let hasBanner = false;
  let lastModifiedDaysAgo: number | null = null;
  try {
    const st = await fs.stat(agentsMdPath);
    if (st.isFile()) {
      present = true;
      bytes = st.size;
      const raw = await fs.readFile(agentsMdPath, "utf8");
      hasBanner = BANNER_PATTERN.test(raw);
      const ms = Date.now() - st.mtimeMs;
      lastModifiedDaysAgo = Math.floor(ms / (1000 * 60 * 60 * 24));
    }
  } catch {
    // absent
  }

  const checks: DoctorCheck[] = [
    {
      name: "node-version",
      ok: nodeOk,
      detail: nodeOk
        ? `${nodeVersion} (>=${REQUIRED_NODE_MAJOR} required)`
        : `${nodeVersion} — agentsmd requires Node >=${REQUIRED_NODE_MAJOR}`,
    },
    {
      name: "agents-md-present",
      ok: present,
      detail: present ? `${bytes} bytes at ${agentsMdPath}` : `not found at ${agentsMdPath} — run \`agentsmd init --apply\``,
    },
    {
      name: "sibling-configs",
      ok: true,
      detail:
        configs.filter((c) => c.kind !== "agents-md").length === 0
          ? "no sibling configs detected"
          : `${configs.filter((c) => c.kind !== "agents-md").length} sibling config(s): ${configs
              .filter((c) => c.kind !== "agents-md")
              .map((c) => c.label)
              .join(", ")}`,
    },
  ];

  const ok = checks.every((c) => c.ok);

  return {
    target: root,
    node: { version: nodeVersion, ok: nodeOk, required: `>=${REQUIRED_NODE_MAJOR}` },
    agentsmd,
    configs,
    agentsMd: { present, bytes, hasBanner, lastModifiedDaysAgo },
    checks,
    ok,
  };
}
